---

- name: Deploy delivercute app
  hosts: tag_Name_delivercute
  remote_user: ubuntu
  gather_facts: yes
  vars_files:
    - delivercute_vars.yml

  tasks:
    - name: Get DB Hostvars
      set_fact:
        db_host: "{{ hostvars[groups[rds_db_name][0]] }}"

    - name: Set DB URL
      set_fact:
        db_url: "{{ db_host.ec2_engine }}://{{ db_host.ec2_master_username }}:{{ db_password }}@{{ db_host.ec2__address }}:{{ db_host.ec2__port }}/{{ db_host.ec2_DBName }}"

    # - name: Execute On-Deploy Script
    #   sudo: yes
    #   command: "python {{ django_home }}/on_deploy.py"
    #   environment:
    #     DATABASE_URL: "{{ db_url }}"
    #     SECRET_KEY: "{{ secret_key }}"
    #     DJANGO_SETTINGS_MODULE: "{{ settings_file }}"
    #     PROJECT_EMAIL: "{{ project_email }}"
    #     PROJECT_PASSWORD: "{{ project_password }}"
    #     PROJECT_APP_PASSWORD: "{{ project_app_password }}"

    # - name: Execute Test Run of On-Schedule Script
    #   sudo: yes
    #   command: "python {{ django_home }}/on_schedule.py DEBUG"
    #   environment:
    #     DATABASE_URL: "{{ db_url }}"
    #     SECRET_KEY: "{{ secret_key }}"
    #     DJANGO_SETTINGS_MODULE: "{{ settings_file }}"
    #     PROJECT_EMAIL: "{{ project_email }}"
    #     PROJECT_PASSWORD: "{{ project_password }}"
    #     PROJECT_APP_PASSWORD: "{{ project_app_password }}"

    - name: Creates hourly cronjob to send emails to subscribers
      cron: minute="0"
        name="Deliver Cute"
        user="ubuntu"
        job="python {{ django_home }}/on_schedule.py"
    - name: Insert secret key into cron env
      cronvar: user="ubuntu" name=SECRET_KEY value="{{ secret_key }}"
    - name: Insert Django settings module into cron env
      cronvar: user="ubuntu" name=DJANGO_SETTINGS_MODULE value="{{ settings_file }}"
    - name: Insert app email address into cron env
      cronvar: user="ubuntu" name=PROJECT_EMAIL value="{{ project_email }}"
    - name: Insert app email password into cron env
      cronvar: user="ubuntu" name=PROJECT_APP_PASSWORD value="{{ project_password }}"
    - name: Insert Postgres database URL inro cron env
      cronvar: user="ubuntu" name=DATABASE_URL value="{{ db_url }}"

- include: deploy_django.yml project_var_file=delivercute_vars.yml

#pre_tasks
#post_tasks