---

- name: Deploy {{ project_name }} Django Project
  hosts: tag_Name_{{ project_name }}
  remote_user: ubuntu
  gather_facts: yes
  environment:
      SECRET_KEY: "{{ secret_key }}"
      DJANGO_SETTINGS_MODULE: "{{ settings_file }}"
      PROJECT_EMAIL: "{{ project_email }}"
      PROJECT_PASSWORD: "{{ project_password }}"
      PROJECT_APP_PASSWORD: "{{ project_app_password }}"

  roles:
    - role: get_aws_db_url
    - role: django
      environment:
        DATABASE_URL: "{{ db_url }}"
    - role: gunicorn
    - role: jdauphant.nginx
      sudo: yes
      nginx_sites:
        default:
          - listen 80
          - server_name "{{ ec2_public_dns_name }}"
          - access_log "/var/log/nginx/django.log"
          - location / {
              proxy_pass http://127.0.0.1:8000;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
          - location /static { alias {{ django_home }}/static; }
          - location /media { alias {{ django_home }}/media; }
    # - role: "{{ project_name }}_on_deploy"
    #   environment:
    #     DATABASE_URL: "{{ db_url }}"
