---

- name: Execute On-Deploy Script
  sudo: yes
  command: "python {{ django_home }}/on_deploy.py"

- name: Execute Test Run of On-Schedule Script
  sudo: yes
  command: "python {{ django_home }}/on_schedule.py DEBUG"

- name: Creates hourly cronjob to send emails to subscribers
  cron: minute="0"
    name="Deliver Cute"
    user="ubuntu"
    job="python {{ django_home }}/on_schedule.py"
- name: Insert secret key into cron env
  cronvar: user="ubuntu" name=SECRET_KEY value="{{ secret_key }}"
- name: Insert Django settings module into cron env
  cronvar: user="ubuntu" name=DJANGO_SETTINGS_MODULE value="{{ settings_file }}"
- name: Insert app email address into cron env
  cronvar: user="ubuntu" name=PROJECT_EMAIL value="{{ project_email }}"
- name: Insert email password into cron env
  cronvar: user="ubuntu" name=PROJECT_PASSWORD value="{{ project_password }}"
- name: Insert app email password into cron env
  cronvar: user="ubuntu" name=PROJECT_APP_PASSWORD value="{{ project_app_password }}"
- name: Insert Postgres database URL inro cron env
  cronvar: user="ubuntu" name=DATABASE_URL value="{{ db_url }}"